"""add organization_address

Revision ID: 0788a427058b
Revises: e2585bc8bd56
Create Date: 2026-06-15 23:39:21.284071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0788a427058b'
down_revision: Union[str, Sequence[str], None] = 'e2585bc8bd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_requests', sa.Column('organization_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_requests', 'organization_address')
    # ### end Alembic commands ###
