"""add teacher counts

Revision ID: 4e81433e45c5
Revises: d4f328b7394d
Create Date: 2026-06-15 23:48:10.888740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e81433e45c5'
down_revision: Union[str, Sequence[str], None] = 'd4f328b7394d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_requests', sa.Column('total_teachers', sa.Integer(), nullable=True))
    op.add_column('visit_requests', sa.Column('female_teachers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_requests', 'female_teachers')
    op.drop_column('visit_requests', 'total_teachers')
    # ### end Alembic commands ###
