"""add letter number

Revision ID: a066020273c6
Revises: dd57c2a17c0d
Create Date: 2026-06-16 00:04:21.523472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a066020273c6'
down_revision: Union[str, Sequence[str], None] = 'dd57c2a17c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_requests', sa.Column('letter_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_requests', 'letter_number')
    # ### end Alembic commands ###
