"""add_annotations_to_report

Revision ID: b1cc77e95c17
Revises: a066020273c6
Create Date: 2026-06-16 01:11:25.933950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1cc77e95c17'
down_revision: Union[str, Sequence[str], None] = 'a066020273c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('annotations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'annotations')
    # ### end Alembic commands ###
