"""add guide_count and restore settings

Revision ID: d4f328b7394d
Revises: 0788a427058b
Create Date: 2026-06-15 23:47:00.076732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f328b7394d'
down_revision: Union[str, Sequence[str], None] = '0788a427058b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_requests', sa.Column('guide_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_requests', 'guide_count')
    # ### end Alembic commands ###
