"""add tracking token

Revision ID: dd57c2a17c0d
Revises: 4e81433e45c5
Create Date: 2026-06-15 23:55:29.035913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd57c2a17c0d'
down_revision: Union[str, Sequence[str], None] = '4e81433e45c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_requests', sa.Column('tracking_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_visit_requests_tracking_token'), 'visit_requests', ['tracking_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_requests_tracking_token'), table_name='visit_requests')
    op.drop_column('visit_requests', 'tracking_token')
    # ### end Alembic commands ###
