"""add visitor_type

Revision ID: e2585bc8bd56
Revises: de590194aeca
Create Date: 2026-06-15 23:32:33.501927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e2585bc8bd56'
down_revision: Union[str, Sequence[str], None] = 'de590194aeca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_requests', sa.Column('visitor_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_requests', 'visitor_type')
    # ### end Alembic commands ###
